version: '3'
volumes:
  solr_data_vol:
  geoblacklight_src:
  geoblacklight_db:
  gem_cache:
  node_modules:

services:
  geoblacklight:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: "not_a_secret"
      SOLR_URL: http://solr:8983/solr/geoblacklight
      GEOBLACKLIGHT_POSTGRES_USER: postgres
      GEOBLACKLIGHT_POSTGRES_PASSWORD: postgres
      GEOBLACKLIGHT_POSTGRES_HOST: db
      GEOBLACKLIGHT_POSTGRES_PORT: 5432

    volumes:
      - ./app:/usr/src/app
      - geoblacklight_db:/usr/src/db
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - solr

  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    command:
      - solr-precreate
      - geoblacklight
      - /opt/solr/server/solr/configsets/geoblacklight/conf
    volumes:
      - solr_data_vol:/var/solr/data
    ports:
      - "8983:8983"

