development:
  adapter: Blacklight::GlobusSearch::Repository
  url: "https://search.api.globus.org/v1/index/ecfd43ee-165f-47be-b82e-2a9e496f0264/search"
test: &test
  adapter: Blacklight::GlobusSearch::Repository
  url: "https://search.api.globus.org/v1/index/ecfd43ee-165f-47be-b82e-2a9e496f0264/search"
production:
  adapter: Blacklight::GlobusSearch::Repository
  url: "https://search.api.globus.org/v1/index/ecfd43ee-165f-47be-b82e-2a9e496f0264/search"
